Improve-template-api
keep-secrets/template-api pull request #3
Opened 2022-07-12 14:10 UTC by AlfonMnz

Finish the issue improve template api

2022-07-12 14:24 UTC, EsteveSegura requested changes
Algún punto a revisar.

2022-07-12 14:24 UTC, EsteveSegura commented on src/package.json
> +    "test": "NODE_ENV=test jest --passWithNoTests --maxWorkers=1"
can we add 2 commands?

"pretest" that runs eslint .
and "lint" that runst eslint .

2022-07-12 14:24 UTC, EsteveSegura commented on src/infrastructure/gracefulStopper.js
> +function registerGracefulStopper() {
registerGracefulStopper, its a weird name?
Can we improve that?

2022-07-12 14:24 UTC, EsteveSegura commented on src/infrastructure/gracefulStopper.js
> +const signals = ['SIGTERM', 'SIGINT'];
add SIGUSR1 and SIGUSR2

2022-07-12 14:24 UTC, EsteveSegura commented on src/infrastructure/gracefulStopper.js
> +        process.exit();
process.exit(0);
just to make sure that exists with an OK code.

2022-07-12 14:24 UTC, EsteveSegura commented on src/infrastructure/gracefulStopper.js
> +        dbHandler.disconnect();
Can we do logs after and before of stopping the server? just for having a visual confirmation

2022-07-12 14:24 UTC, EsteveSegura commented on src/index.js
> +gracefulStopper.registerGracefulStopper();
It looks strange to call this method, the execution of the method is obscure.

The feeling is that when this method is called, the server will stop.

We can add the signals and the logic to listen to the process in the index.js and in the gracefulStopper we only leave the logic related to stop the services.

2022-07-12 14:24 UTC, EsteveSegura commented on README.md
> +In db handler check ToDo and set correct collection
Can we provide a little more information?

Files to edit, lines, fields. Something similar to a checklist, to be sure that we have configured the scaffold correctly.

2022-07-12 14:24 UTC, EsteveSegura commented on src/index.js
> +app.get('/internal/liveness', (req, res) => {
These are controllers,
we'll have to move this into infrastructure/http/internal

2022-07-12 14:24 UTC, EsteveSegura commented on src/index.js
> +  if (dbHandler.getInstance()) return res.status(200).json({response: "I'm ready"});
This part of the logic is completely coupled to mongodb, can we make it a bit more agnostic?

2022-07-12 14:24 UTC, EsteveSegura commented on src/infrastructure/config/index.js
> +  keepsecrets:{
this is really needed for the scaffold?

2022-07-12 14:38 UTC, AlfonMnz commented on src/index.js
> +  if (dbHandler.getInstance()) return res.status(200).json({response: "I'm ready"});
I don't know how want implement it

2022-07-12 14:47 UTC, EsteveSegura commented on src/infrastructure/config/index.js
> +  keepsecrets:{
Dont remove everythin', just the JWT!

2022-07-12 14:54 UTC, EsteveSegura commented on src/index.js
> +  if (dbHandler.getInstance()) return res.status(200).json({response: "I'm ready"});
You need to check an array and that everything inside is valid.
Somethign like that

```js
router.get('/readiness', (req, res) => {
    let ready = true;
    const dbHandler = container.resolve('mongoDbHandler');
    const cacheHandler = container.resolve('redisDbHandler');
    const thirdPartyService = container.resolve('thirdParty');

    const services = [dbHandler.getInstance(),cacheHandler.alive(), thirdPartyService.isConnected]
    // loop in services with foreach, and if everyting passes, its ok.
    services.forEach((svc) => {
       if(!svc) {
           ready = false;
       }
    })
    
    if (ready)
          200
     else
          500
});
```

2022-07-12 14:54 UTC, EsteveSegura commented on src/index.js
> +  if (dbHandler.getInstance()) return res.status(200).json({response: "I'm ready"});
Also **readyness** is a typo

2022-07-23 21:16 UTC, EsteveSegura approved these changes
Well done! Thanks

2022-07-23 21:16 UTC, EsteveSegura commented on src/infrastructure/http/internal-controller.js
> +        if (!ready) return res.status(500).json({response: "Not ready"});
avoid oneliners

2022-07-23 21:17 UTC, merged